In [45]:
import numpy as np
import pandas as pd

# 1
 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [46]:
a = np.arange(1, 11, 1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [47]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 3
Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [48]:
c = np.random.randint(1, 11, size=(5, 5))
c

array([[ 8,  8,  2,  4,  1],
       [10,  5,  5,  3,  6],
       [10,  6,  2,  1,  2],
       [ 6, 10, 10,  1,  8],
       [ 6,  2,  1,  1,  9]])

# 4
Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [49]:
d = np.random.random((4, 4))
d

array([[0.39740649, 0.03332008, 0.95959257, 0.06641632],
       [0.47595312, 0.08340397, 0.27324732, 0.64276754],
       [0.62157786, 0.68172887, 0.81336723, 0.02321491],
       [0.85402349, 0.21051005, 0.88730957, 0.65265709]])

# 5
Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [50]:
e = np.random.randint(1, 11, size=5)
f = np.random.randint(1, 11, size=5)

## Addition

In [51]:
g = e + f
g

array([ 9, 15, 13,  9, 13])

## Subtraction

In [52]:
g = e - f
g

array([-1,  1,  1, -7,  7])

## Multiplication

In [53]:
g = e * f
g

array([20, 56, 42,  8, 30])

# 6
Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [54]:
h = np.random.randint(1, 11, size=7)
i = np.random.randint(1, 11, size=7)
j = np.dot(h, i)
j

197

# 7
Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [55]:
k = np.random.randint(1, 11, size=(2, 2))
l = np.random.randint(1, 11, size=(2, 3)) 
m = np.dot(k, l)
m

array([[ 85,  81, 111],
       [ 75,  95,  95]])

# 8
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [56]:
n = np.random.randint(1, 11, size=(3, 3))
n_inv = np.linalg.inv(n)
n_inv

array([[ 0.5 ,  0.5 , -0.75],
       [-1.5 , -0.5 ,  1.75],
       [ 4.5 ,  0.5 , -4.25]])

# 9
Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [57]:
o = np.random.random((4, 4))
o_T = o.T
o_T

array([[0.66955119, 0.04298854, 0.74251169, 0.62650261],
       [0.79779771, 0.12331773, 0.04548913, 0.71318147],
       [0.85555434, 0.33731512, 0.68723682, 0.51150367],
       [0.8028208 , 0.80396837, 0.87535519, 0.01390972]])

# 10
Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [58]:
p = np.random.randint(1, 11, size=(3, 4))
q = np.random.randint(1, 11, 4)
print(p, q)
r = np.dot(p, q)
r

[[10  2  1  7]
 [ 1 10  9  7]
 [ 8  1  5  9]] [ 7 10  4  4]


array([122, 171, 122])

# 11
Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [59]:
s = np.random.random((2, 3))
t = np.random.random(3)
u = np.dot(s, t)
u

array([0.26238006, 0.03856728])

# 12
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [60]:
v = np.random.randint(1, 11, size=(2, 2))
w = np.random.randint(1, 11, size=(2, 2))
x = v * w
x

array([[100,  24],
       [100,  63]])

# 13
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [61]:
y = np.random.randint(1, 11, size=(2, 2))
z = np.random.randint(1, 11, size=(2, 2))
aa = np.dot(y, z)
aa

array([[28, 25],
       [58, 73]])

# 14
Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [62]:
bb = np.random.randint(1, 101, size=(5, 5))
#cc = np.sum(bb)
cc = bb.sum()
cc

1213

# 15
Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [66]:
dd = np.random.randint(1, 11, size=(4, 4))
ee = np.random.randint(1, 11, size=(4, 4))
ff = dd - ee
ff

array([[-3,  1, -3,  3],
       [ 6,  6, -2, -2],
       [-4, -2, -3, -9],
       [ 5, -1, -1, -4]])

# 16
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [78]:
gg = np.random.random((3, 3))
hh = gg.sum(axis=1).reshape(3, 1)
hh

array([[1.53393117],
       [1.51840182],
       [1.48387489]])

# 17
Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [89]:
ii = np.random.randint(1, 11, size=(3, 4))
jj = ii**2
jj

array([[ 25, 100, 100,  64],
       [  4, 100,   9, 100],
       [ 25,   9, 100,  49]])

# 18
Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [109]:
kk = np.random.randint(1, 51, 4)
ll = np.sqrt(kk)
#ll = np.power(kk, 1/2)
print(ll)

[5.74456265 3.46410162 6.78232998 3.74165739]
[5.74456265 3.46410162 6.78232998 3.74165739]
